# -*- coding: utf-8 -*-
"""untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Faryal88/59195f21d1fe269e8325a3e5664a6618/untitled0.ipynb
"""



"""# **GIAIC All Python Projects**

This repository showcases a variety of Python projects developed as part of the GIAIC AI-101 course. Each project highlights different programming concepts and real-world applications, ranging from simple Python games to interactive web applications built with Streamlit.

# **📜 Project List**

1. Unit Converter
🔗https://github.com/Faryal88/Unit-Converter-Python.git

2. Calculator
🔗https://github.com/Faryal88/python-Calculator.git

3. Password Strength Meter
🔗https://github.com/Faryal88/Password-Strength-Meter-Python.git

4. BMI Calculator
🔗https://github.com/Faryal88/BMI-Calculator.git

5. Number Guessing Game
🔗https://github.com/Faryal88/-Number-Guessing-Game.git

6. Growth Mindset
🔗https://github.com/Faryal88/python-growth.git
"""